

static unsigned char const yystos[66] = {
    (unsigned char const)0,  (unsigned char const)23, (unsigned char const)0,
    (unsigned char const)5,  (unsigned char const)6,  (unsigned char const)7,
    (unsigned char const)8,  (unsigned char const)9,  (unsigned char const)11,
    (unsigned char const)12, (unsigned char const)13, (unsigned char const)14,
    (unsigned char const)15, (unsigned char const)16, (unsigned char const)17,
    (unsigned char const)18, (unsigned char const)24, (unsigned char const)25,
    (unsigned char const)26, (unsigned char const)27, (unsigned char const)28,
    (unsigned char const)29, (unsigned char const)30, (unsigned char const)31,
    (unsigned char const)32, (unsigned char const)20, (unsigned char const)4,
    (unsigned char const)17, (unsigned char const)18, (unsigned char const)4,
    (unsigned char const)6,  (unsigned char const)8,  (unsigned char const)11,
    (unsigned char const)13, (unsigned char const)14, (unsigned char const)15,
    (unsigned char const)5,  (unsigned char const)6,  (unsigned char const)8,
    (unsigned char const)10, (unsigned char const)11, (unsigned char const)12,
    (unsigned char const)13, (unsigned char const)14, (unsigned char const)15,
    (unsigned char const)17, (unsigned char const)19, (unsigned char const)21,
    (unsigned char const)3,  (unsigned char const)17, (unsigned char const)20,
    (unsigned char const)17, (unsigned char const)18, (unsigned char const)17,
    (unsigned char const)18, (unsigned char const)18, (unsigned char const)18,
    (unsigned char const)10, (unsigned char const)17, (unsigned char const)19,
    (unsigned char const)33, (unsigned char const)21, (unsigned char const)18,
    (unsigned char const)18, (unsigned char const)17, (unsigned char const)33};
