

static struct numname numname_table[35] = {
    {1,
     {(char const)'H', (char const)'U', (char const)'P', (char const)'\000'}},
    {2,
     {(char const)'I', (char const)'N', (char const)'T', (char const)'\000'}},
    {3,
     {(char const)'Q', (char const)'U', (char const)'I', (char const)'T',
      (char const)'\000'}},
    {4,
     {(char const)'I', (char const)'L', (char const)'L', (char const)'\000'}},
    {5,
     {(char const)'T', (char const)'R', (char const)'A', (char const)'P',
      (char const)'\000'}},
    {6,
     {(char const)'A', (char const)'B', (char const)'R', (char const)'T',
      (char const)'\000'}},
    {8,
     {(char const)'F', (char const)'P', (char const)'E', (char const)'\000'}},
    {9,
     {(char const)'K', (char const)'I', (char const)'L', (char const)'L',
      (char const)'\000'}},
    {7,
     {(char const)'B', (char const)'U', (char const)'S', (char const)'\000'}},
    {11,
     {(char const)'S', (char const)'E', (char const)'G', (char const)'V',
      (char const)'\000'}},
    {13,
     {(char const)'P', (char const)'I', (char const)'P', (char const)'E',
      (char const)'\000'}},
    {14,
     {(char const)'A', (char const)'L', (char const)'R', (char const)'M',
      (char const)'\000'}},
    {15,
     {(char const)'T', (char const)'E', (char const)'R', (char const)'M',
      (char const)'\000'}},
    {10,
     {(char const)'U', (char const)'S', (char const)'R', (char const)'1',
      (char const)'\000'}},
    {12,
     {(char const)'U', (char const)'S', (char const)'R', (char const)'2',
      (char const)'\000'}},
    {17,
     {(char const)'C', (char const)'H', (char const)'L', (char const)'D',
      (char const)'\000'}},
    {23,
     {(char const)'U', (char const)'R', (char const)'G', (char const)'\000'}},
    {19,
     {(char const)'S', (char const)'T', (char const)'O', (char const)'P',
      (char const)'\000'}},
    {20,
     {(char const)'T', (char const)'S', (char const)'T', (char const)'P',
      (char const)'\000'}},
    {18,
     {(char const)'C', (char const)'O', (char const)'N', (char const)'T',
      (char const)'\000'}},
    {21,
     {(char const)'T', (char const)'T', (char const)'I', (char const)'N',
      (char const)'\000'}},
    {22,
     {(char const)'T', (char const)'T', (char const)'O', (char const)'U',
      (char const)'\000'}},
    {31,
     {(char const)'S', (char const)'Y', (char const)'S', (char const)'\000'}},
    {29,
     {(char const)'P', (char const)'O', (char const)'L', (char const)'L',
      (char const)'\000'}},
    {26,
     {(char const)'V', (char const)'T', (char const)'A', (char const)'L',
      (char const)'R', (char const)'M', (char const)'\000'}},
    {27,
     {(char const)'P', (char const)'R', (char const)'O', (char const)'F',
      (char const)'\000'}},
    {24,
     {(char const)'X', (char const)'C', (char const)'P', (char const)'U',
      (char const)'\000'}},
    {25,
     {(char const)'X', (char const)'F', (char const)'S', (char const)'Z',
      (char const)'\000'}},
    {6,
     {(char const)'I', (char const)'O', (char const)'T', (char const)'\000'}},
    {17,
     {(char const)'C', (char const)'L', (char const)'D', (char const)'\000'}},
    {30,
     {(char const)'P', (char const)'W', (char const)'R', (char const)'\000'}},
    {28,
     {(char const)'W', (char const)'I', (char const)'N', (char const)'C',
      (char const)'H', (char const)'\000'}},
    {29, {(char const)'I', (char const)'O', (char const)'\000'}},
    {16,
     {(char const)'S', (char const)'T', (char const)'K', (char const)'F',
      (char const)'L', (char const)'T', (char const)'\000'}},
    {0,
     {(char const)'E', (char const)'X', (char const)'I', (char const)'T',
      (char const)'\000'}}};
